version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB0:/dev/ttyUSB1"
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
